---
repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: terraform-fmt
        args:
          - -diff
          - -check
          - -recursive
      - id: terraform-validate
      - id: tflint
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.130
    hooks:
      - id: checkov
        args:
          - "--config-file"
          - "checkov.yaml"
  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.41.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-symlinks
